---
- name: update homebrew
  homebrew: update_homebrew=yes
  notify:
    - upgrade homebrew packages

- name: initialize brew taps
  homebrew_tap: tap={{ brew_taps }} state=present

- name: install homebrew packages
  homebrew: name={{ brew_packages }} state=present
