---

fonts:
  - fonts/meslo_lg_m_regular_for_powerline.ttf
  - fonts/cascadia.ttf

dots:
  - ~/.ssh

links:
  - source: ~/dotfiles/.gitconfig
    dest: ~/.gitconfig

  - source: ~/dotfiles/.gitignore_global
    dest: ~/.gitignore_global

  - source: ~/dotfiles/.vimrc
    dest: ~/.vimrc

  - source: ~/dotfiles/.zshrc
    dest: ~/.zshrc

  - source: ~/dotfiles/.tmux.conf
    dest: ~/.tmux.conf

  - source: ~/dotfiles/.guard.rb
    dest: ~/.guard.rb

  - source: ~/dotfiles/.alacritty.yml
    dest: ~/.alacritty.yml

