---
- name: install pyenv packages
  homebrew: name={{ item }} state=present
  with_items: "{{ pyenv_packages }}"

- name: install pyenv-pip-rehash
  git:
    repo: https://github.com/yyuu/pyenv-pip-rehash.git
    dest: ~/.pyenv/plugins/pyenv-pip-rehash
    force: yes

- name: install python {{ python2_version }}
  command: ~/.pyenv/bin/pyenv install {{ python2_version }}
  args:
    creates: ~/.pyenv/versions/{{ python2_version }}
  notify: update default python

- name: install python {{ python2_version }} packages
  pip:
    name: "{{ item }}"
    state: latest
    executable: ~/.pyenv/versions/{{ python2_version }}/bin/pip
    chdir: ~/.pyenv/versions/{{ python2_version }}
  with_items: "{{ python2_packages }}"
  notify: update pyenv shims
  environment:
    PYTHONPATH:

- name: install python {{ python3_version }}
  command: ~/.pyenv/bin/pyenv install {{ python3_version }}
  args:
    creates: ~/.pyenv/versions/{{ python3_version }}
  notify: update default python

- name: install python {{ python3_version }} packages
  pip:
    name: "{{ item }}"
    state: latest
    executable: ~/.pyenv/versions/{{ python3_version }}/bin/pip
    chdir: ~/.pyenv/versions/{{ python3_version }}
  with_items: "{{ python3_packages }}"
  notify: update pyenv shims
  environment:
    PYTHONPATH:
