---
- name: install pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: ~/.pyenv
    force: yes

- name: install pyenv-pip-rehash
  git:
    repo: https://github.com/yyuu/pyenv-pip-rehash.git
    dest: ~/.pyenv/plugins/pyenv-pip-rehash
    force: yes

- name: install python
  command: ~/.pyenv/bin/pyenv install {{ item }}
  args:
    creates: ~/.pyenv/versions/{{ item }}
  with_items: "{{ python_versions }}"
  notify: update default python

- name: install python packages
  pip:
    name: "{{ pip_packages }}"
    state: present
    executable: ~/.pyenv/versions/{{ python3_version }}/bin/pip
    chdir: ~/.pyenv/versions/{{ python3_version }}
  notify: update pyenv shims
  environment:
    PYTHONPATH:
