---
- name: install zsh packages
  homebrew: name={{ zsh_packages }} state=present

- name: ensure zsh is in /etc/shells
  become: yes
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/zsh
    state: present

- name: change default shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh

- name: cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    force: yes
