---
- include: "custom/zsh.yml"
# - include: "custom/nodejs.yml"
# - include: "custom/elm.yml"
- include: "custom/go.yml"
- include: "custom/python.yml"
- include: "custom/ruby.yml"
- include: "custom/elixir.yml"
- include: "custom/scala.yml"
- include: "custom/kubernetes.yml"
- include: "custom/phabricator.yml"
