---
# custom/python

- name: update default python
  command: ~/.pyenv/bin/pyenv global {{ default_python_version }}

- name: update pyenv shims
  command: ~/.pyenv/bin/pyenv rehash

# custom/ruby

- name: update default ruby
  command: ~/.rbenv/bin/rbenv global {{ default_ruby_version }}

- name: update rbenv shims
  command: ~/.rbenv/bin/rbenv rehash
