---
- name: clone Vundle
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    force: yes

- name: install/update VIM plugins
  shell: vim +PluginInstall! +qall

- name: clean VIM plugins
  shell: vim +PluginClean! +qall

- name: initial nvim directory
  file:
    path: "~/.config/nvim"
    state: directory

- name: copy nvim config
  copy:
    src: files/nvim/init.vim
    dest: ~/.config/nvim/
    force: yes

- name: install/update VIM plugins for neovim
  shell: nvim +PluginInstall! +qall

- name: clean VIM plugins for neovim
  shell: nvim +PluginClean! +qall
