---
- name: clone Vundle
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    force: yes

- name: install/update VIM plugins
  shell: vim +PluginInstall! +qall
