---
brew_taps:
  - homebrew/cask
  - homebrew/core
  - homebrew/cask-fonts
  - datawire/blackbird
  - heroku/brew

brew_packages:
  - autojump
  - awscli
  - ctags
  - exercism
  - fish
  - fswatch
  - fzf
  - gpg
  - heroku
  - htop
  - hyperkit
  - libxml2
  - mas
  - minikube
  - neovim
  - postgresql
  - the_silver_searcher
  - tree

cask_packages:
  - 1password
  - alacritty
  - alfred
  - appcleaner
  - brave-browser
  - dash
  - discord
  - docker
  - drawio
  - figma
  - firefox
  - font-jetbrains-mono
  - google-backup-and-sync
  - google-chrome
  - google-cloud-sdk
  - iterm2
  - ngrok
  - numi
  - oracle-jdk
  - postico
  - postman
  - sequel-pro
  - slack
  - spotify
  - telegram
  - visual-studio-code
  - whatsapp

mas_packages:
  - 1091189122  # Bear
  - 441258766   # Magnet
  - 539883307   # LINE

# custom/zsh

zsh_packages:
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting

# custom/node

yarn_packages:
  - neovim
  - pm2
  - dockly

# custom/elm

elm_packages:
  - elm-test
  - elm-oracle
  - elm-format
  - create-elm-app

# custom/python

python_versions:
  - 3.8.4
  - 3.9.1

default_python_version: 3.8.4

pip_packages:
  - pynvim
  - pip
  - virtualenv
  - pipenv
  - black

# custom/ruby

ruby_versions:
  - 2.7.2

default_ruby_version: 2.7.2

gem_packages:
  - neovim
  - bundler
  - rails
  - pry

# custom/kubernetes

kubernetes_packages:
  - kubernetes-cli
  - kubernetes-helm
  - kubectx
