---
brew_taps:
  - datawire/blackbird
  - homebrew/cask
  - homebrew/core

brew_packages:
  - autojump
  - fish
  - fswatch
  - postgresql
  - libxml2

  # https://github.com/ggreer/the_silver_searcher
  - the_silver_searcher

cask_taps:
  - homebrew/cask

cask_packages:
  - 1password
  - alfred
  - appcleaner
  - alacritty
  - discord
  - docker
  - drawio
  - dropbox
  - firefox
  - google-backup-and-sync
  - google-chrome
  - google-cloud-sdk
  - iterm2
  - ngrok
  - numi
  - postico
  - postman
  - sequel-pro
  - sizeup
  - sourcetree
  - spotify
  - sublime-text
  - telegram
  - transmission
  - trezor-bridge
  - visual-studio-code
  - vlc

# custom/zsh

zsh_packages:
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting

# custom/node

node_package: node

node_packages:
  - yarn

npm_packages:
  - pm2
  - dockly

# custom/go

go_package: go

go_packages:
  - dep

# custom/python

python_versions:
  - 2.7.13
  - 3.6.5

python3_version: 3.6.5

pip_packages:
  - pip
  - pipenv
  - virtualenv
  - ipython
  - awscli

# custom/ruby

ruby_version: 2.5.3

gem_packages:
  - bundler
  - pry

# custom/elixir

elixir_package: elixir

# custom/kubernetes

kubernetes_packages:
  - kubectl
  - kubectx
  - kubernetes-cli
  - kubernetes-helm

